### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by Eboon-05**
This Spanish translation doesn't have accents marks. It's the only problem because I don't really know C and C++ or what a .ts file is. I only know JavaScript. But I really want to help, so if someone else want to translate to spanish, i hope he/she will do better than me.

### CODE REVIEW

**Comment by ghost** [comment]
Looks great, you did everything perfect! Thank you! Could you translate the README as well?

**Comment by Eboon-05** [comment]
> Looks great, you did everything perfect! Thank you! Could you translate the README as well?

I will.

**Comment by Eboon-05** [comment]
Hey! I have a problem. In the README, there is a part of [almost], this almost is an url or something like that (I think). In spanish I need to write "casi" on its place. But I don't know how it is going to see here in github, or if some part of the code is going to break. If you can ensure that there is no problem with that, I will continue.

**Comment by Eboon-05** [comment]
I had to move the README to the root folder because, if I keep it in the Translations folder License doesn't work properly. But now it does. I hope this translation is useful to you! I will install this app in my UbuntuDDE. I'll watch your proyect ;)

**Comment by Eboon-05** [comment]
I know this has nothing so see with translation, but is like a bug report.
After updating, it jumped. I don't know C so I can't help with this, I can only translate :(

Screen Capture_20201125133339

**Comment by ghost** [comment]
> I know this has nothing so see with translation, but is like a bug report.
> After updating, it jumped. I don't know C so I can't help with this, I can only translate :(
> 
> Screen Capture_20201125133339
> 

Fixed in latest commit (90c48a7)! Pushing an update today. Thank you so much for all of your help!

**Comment by ghost** [comment]
When you moved it to the root folder, it doesn't seem like it was moved. I don't see any README.es.md or anything like that. Did you accidentally delete it or move it somewhere else?

**Comment by Eboon-05** [comment]
Now there is. Sorry for the problem, is my first time collaborating with a GitHub project and English is not my native language. The only problem is that I created the file by Windows, and now I'm uploading it by Linux, so there is a commit for the whole branch. All the files are exactly the same, but Git made a commit for all of them. The only thing i did was create the translations file anyway. If you want I can upload them to some cloud drive service like mediafire and you make a push manually.

**Comment by ghost** [comment]
> Now there is. Sorry for the problem, is my first time collaborating with a GitHub project and English is not my native language. The only problem is that I created the file by Windows, and now I'm uploading it by Linux, so there is a commit for the whole branch. All the files are exactly the same, but Git made a commit for all of them. The only thing i did was create the translations file anyway. If you want I can upload them to some cloud drive service like mediafire and you make a push manually.

No, this is perfect! The first time contributing is hard and everyone makes mistakes. This is my first time releasing anything like this, and I'm learning along the way too. Thank you for contributing!

**Comment by Eboon-05** [comment]
If you make a development branch to test the translations, I'd feel very happy of contribute. And if you update something, feel free to ask me for spanish translate.

**Review by ghost — APPROVED** [review]

**Pull request merged**
