### PR TITLE
Add English and Deutsche reference in the Spanish README

### PR DESCRIPTION
**Pull request by Eboon-05**
Hi again! I saw you did the same for the English README, so I decided to make this one.

Here a preview:
image

### CODE REVIEW

**Comment by ghost** [comment]
I was considering doing this, but I'm not sure if it would be the best for more languages. With every new language you have to add it to every other translated README. Do you think it would work to maybe add just the "English" option, because the English README links to the other translations?

**Comment by Eboon-05** [comment]
> I was considering doing this, but I'm not sure if it would be the best for more languages. With every new language you have to add it to every other translated README. Do you think it would work to maybe add just the "English" option, because the English README links to the other translations?

Ok, I will eliminate the Deutsche and add some information for the English. Or maybe we can do a separate file for choosing language of the README's.

**Comment by Eboon-05** [comment]
Now the README says that the english README contains all the translations.

**Comment by ghost** [comment]
People could also just hit the back button or click on "dde-store" at the top which goes to the main README. People have to manually click on the translation they want to go to, so they've seen the language selector before. Do you think it's not intuitive enough?

**Comment by Eboon-05** [comment]
Yes it's intuitive enough, but ins't bad to have another refence. I think we can add something like "Here are more languages" before the languages. Or make a translations.md where will be all the translations and make a reference in README to this file (because if all the translations are in the README, they will get in the way when reading of the english speakers), but not now, there are only 3 languages. It's okay if you don't want, anyway, it's your project.

**Comment by ghost** [comment]
I'm going to close this just for now. If there are too many translated READMEs, I'll take your advice and to move them to a different  file. Thank you for the suggestion!

**Pull request closed without merging**
