### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by Nesewebel**

### CODE REVIEW

**Comment by ghost** [comment]
Thank you so much, looks great! Would you mind translating the README as well?

**Comment by Nesewebel** [comment]
Sure. Should I add a README.de.md for it or how would you do that?

**Comment by ghost** [comment]
README.de.md would be perfect. I'll add a language selector to README.md that links to README.de.md.

**Comment by Nesewebel** [comment]
Hey, sorry I'm struggling a bit with the "What is this?" part. Could you elaborate on what "a web view with the Deepin repos on it" means?

**Comment by ghost** [comment]
It's just a website inside the app that they built. That website only has apps from the Deepin repos on it. If that part is too hard to translate, it's alright if you don't include it!

**Comment by Nesewebel** [comment]
Okay I think I've got it 👍

**Comment by ghost** [comment]
Awesome, thank you!

**Review by ghost — APPROVED** [review]

**Pull request merged**
